### ISSUE TITLE
specifying a procedure for handling discuss list CoC (or other list-specific rule) violations

### ISSUE THREAD

**Issue by ctb** [swcarpentry/board#114]
Taken from https://github.com/swcarpentry/board/issues/111#ref-pullrequest-154002431, I propose:
1. In response to a CoC report or violation of other list-specific rules, the current SCF ExecDir (@jduckles) and any appointed deputy moderators have discretion to set the list emergency moderation bit and initiate a ban or user-specific moderation. These actions will be reported back to the list within 24 hours along with the reasoning behind them.
2. Reported CoC violations on the list can be appealed by e-mailing the SCF steering committee at $blah.
3. A list-specific ban can be extended to any online space managed by the SCF, at the discretion of the Executive Director and the steering committee.

I'm going to pass this on to the discuss@ list in a bit.

(Please read the thread summary for #111 before commenting - see https://github.com/swcarpentry/board/issues/111#issuecomment-217883965 and https://github.com/swcarpentry/board/issues/111#issuecomment-217900748)

**Comment by embray** [comment]
Where would this be specified?  Looks good to me otherwise.

**Comment by ctb** [comment]
I leave that up to the board - I can't keep track of the website stuff :)

**Comment by wrightaprilm** [comment]
Looks fine to me. I'd like to see #3 strengthened. If someone's behavior is bad enough that they aren't allowed on the main list anymore, I don't think I follow the rationale for allowing them to continue posting on other SC mailing lists or the issue tracker.

**Comment by BillMills** [comment]
I agree with @wrightaprilm; not only does a global ban prevent obvious troll tactics, but keeps the management simpler.

**Comment by ctb** [comment]
On Wed, May 11, 2016 at 09:15:45AM -0700, Bill Mills wrote:
> I agree with @wrightaprilm; not only does a global ban prevent obvious troll tactics, but keeps the management simpler.

In the case under question here, I totally agree on an SCF-wide ban because of
the personal e-mail harassment.  But I can imagine situations where public
interaction with the person in question (e.g. where they're confused and polite
about it) could be productive.  I'm personally leary of mandating too much and
removing things from the discretion of the Executive Director, which is why
I phrased it that way.

Any thoughts on this from others?

**Comment by katyhuff** [comment]
I agree a community-wide ban is appropriate in such a case.

But, I also agree with @ctb that specific instances (especially things that
happen very rarely, like CoC violations) are often best handled on a
case-by-case basis by the Exec. Director. The Exec. Director, simply by
their job description, will typically act with involvement input from the
steering committee or the appropriate standing subcommittee where
appropriate.


On Wed, May 11, 2016 at 9:20 AM, C. Titus Brown <notifications@github.com>
wrote:

> On Wed, May 11, 2016 at 09:15:45AM -0700, Bill Mills wrote:
> > I agree with @wrightaprilm; not only does a global ban prevent obvious
> troll tactics, but keeps the management simpler.
>
> In the case under question here, I totally agree on an SCF-wide ban
> because of
> the personal e-mail harassment. But I can imagine situations where public
> interaction with the person in question (e.g. where they're confused and
> polite
> about it) could be productive. I'm personally leary of mandating too much
> and
> removing things from the discretion of the Executive Director, which is why
> I phrased it that way.
>
> Any thoughts on this from others?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/board/issues/114#issuecomment-218511434>
>



-- 
http://katyhuff.github.com

**Comment by BillMills** [comment]
@katyhuff re: the ED doubling as community manager: that has been the default stopgap solution, but community management is definitely out of scope for the ED in the long run - Jonah has more than enough to do as it is. We're looking into more sustainable solutions.

**Comment by katyhuff** [comment]
On Wed, May 11, 2016 at 10:04 AM, Bill Mills <notifications@github.com>
wrote:

> @katyhuff <https://github.com/katyhuff> re: the ED doubling as community
> manager: that has been the default stopgap solution, but community
> management is definitely out of scope for the ED in the long run - Jonah
> has more than enough to do as it is. We're looking into more sustainable
> solutions.
>

@billdoesphysics As I said, I agree that the standing subcommittee as a
support structure is a good idea. I just also agree with @ctb that guiding
these interactions should not be taken out of his capable leadership.
Whether or not it's out of scope for the ED is an interesting question. You
state is as a fact that it's out of scope, but actually, being a leader in
community interactions among volunteers, being a spokesperson in public
forums, and leading outreach were among the key duties we at the core of
the ED job description when we went through the process of hiring Jonah, so
I, like @ctb, would just hesitate to take those authority away from him
with too prescriptive a document. It's up to @jduckles and the steering
committee to change that though, if that's more appropriate now.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/board/issues/114#issuecomment-218524072>
>



-- 
http://katyhuff.github.com

**Comment by BillMills** [comment]
@katyhuff Jonah is welcome to take the lead on any spokespersoning he'd like to set his hand to; alls I'm saying, is that if it consistently falls to the admiral to swab the deck, we are going to have a sparkling clean sinking ship. Our partners deserve the ED's undivided attention, which is why we're angling for a community facing role to soak the majority of internet drama (as already articulated in @ctb point 1 as 'deputy mods' - just want to make sure the emphasis is clearly on the mods, and not getting dumped on @jduckles too hastily).

**Comment by katyhuff** [comment]
On Wed, May 11, 2016 at 11:32 AM, Bill Mills <notifications@github.com>
wrote:

> @katyhuff <https://github.com/katyhuff> Jonah is welcome to take the lead
> on any spokespersoning he'd like to set his hand to; alls I'm saying, is
> that if it consistently falls to the admiral to swab the deck, we are going
> to have a sparkling clean sinking ship. Our partners deserve the ED's
> undivided attention, which is why we're angling for a community facing role
> to soak the majority of internet drama (as already articulated in @ctb
> <https://github.com/ctb> point 1 as 'deputy mods' - just want to make
> sure the emphasis is clearly on the mods, and not getting dumped on
> @jduckles <https://github.com/jduckles> too hastily).
>

I think we're on the same page.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/board/issues/114#issuecomment-218548818>
>



-- 
http://katyhuff.github.com

**Comment by wking** [comment]
On Wed, May 11, 2016 at 11:32:25AM -0700, Bill Mills wrote:
> as already articulated in @ctb point 1 as 'deputy mods' - just want
> to make sure the emphasis is clearly on the mods, and not getting
> dumped on @jduckles too hastily

I'm not sure it makes sense to call out CoC violations and/or mailing
lists in particular.  I'm fine dumping all executive action
(list-management or otherwise [1]) on @jduckles and leaving the
implementation entirely up to him.  Similiarly, reporting
executive-branch actions to the steering committee and/or wider SWC
community seems like a generic thing.  And an appeals process for “I
just heard about an executive / steering-committee action I don't
like” seems like a generic thing.  Can we encode these requirements in
[1,2] without building a narrow workflow that's just for CoC/list
issues?

[1]: https://github.com/swcarpentry/board/blob/master/executive-director.md
[2]: https://github.com/swcarpentry/board/blob/master/committee-roles.md

**Comment by ctb** [comment]
This proposes a significant expansion of this issue and IMO is unlikely to
result in anything anytime soon.  Since the question of who/what/when/why
was explicitly brought up by several people I'd like to just address that.

So, I am -1 on expanding the issue beyond the discuss list, and think that any
later action on that could retroactively be applied to the mailing list quite
easily.

**Comment by wking** [comment]
On Wed, May 11, 2016 at 12:28:29PM -0700, C. Titus Brown wrote:
> This proposes a significant expansion of this issue and IMO is
> unlikely to result in anything anytime soon.

Fair.  Spun off into #115, #116.  Appeals are already somewhat handled
by [1], although that needs genericization along the lines of
swcarpentry/website#374.

[1]: https://github.com/swcarpentry/board/blob/master/issue-escalation.md#issues-requiring-steering-committee-clearance

**Comment by jduckles** [comment]
@wking Based on your spin-offs, should this PR be closed?

**Comment by wking** [comment]
On Wed, May 11, 2016 at 08:35:52PM -0700, Jonah Duckles wrote:
> @wking Based on your spin-offs, should this PR be closed?

Probably not.  I think my spin-offs cover the main ideas in a more
general way, but it's still nice to have a document closer to [1] that
focuses on the specifics.  Besides #115 and #116, I'd like to see:

* issue-escalation.md extended to cover online spaces (along the lines
  of swcarpentry/website#374).

* issue-escalation.md made more clearly actionable by including
  explicit email addresses.  E.g. conduct@software-carpentry.org for
  violations, monitored by the Executive Director (or their deputy).
  And appeal@software-carpentry.org for appeals monitored by both the
  Executive Direcor (or their deputy) and the Steering Committee (or
  one of its members, a new role?).

* A policy / guidelines for CoC enforcement.  Do we keep @ctb's
  24-hour time limit?  Does all enforcement lead to notification in
  the protected channel?  issue-escalation.md is currently covering
  CoC violations in a reporting capacity (“tell us what happened”) and
  not in an enforcement capacity (“I want you to moderate $MEMBER
  today for $VIOLATION”).  The Steering Committee just doesn't move on
  that timescale ;).  So some sort of notes published by the Executive
  Director (or their delegate) about how they intend to manage this
  sort of thing in the sub-week timescale would be good, and probably
  don't belong in issue-escalation.md.

[1]: https://github.com/swcarpentry/board/issues/114#issue-154244303

**Comment by BillMills** [comment]
> Do we keep @ctb's 24-hour time limit? Does all enforcement lead to notification in the protected channel?

yes and yes please. Never drop the hammer without a public teachable moment; concrete punitive action is the single biggest thing that rebuilds trust in community members who feel put off by an infraction - but only if they know the action actually landed.

**Comment by ctb** [comment]
@jduckles I think this is ready for the board; the main points are in the issue header, and I don't see major modifications to them in the following thread (although lots of good discussion). Let me know what I should do from here.

**Comment by karinlag** [comment]
@ctb , I believe you get a board member (the natural person to ask here would be @BillMills ) to put this up on the agenda for the next board meeting.

**Comment by ErinBecker** [comment]
Hi all - please see our new [blog post](http://www.datacarpentry.org/blog/code-of-conduct/) related to this issue.

**Comment by ErinBecker** [comment]
Hi all - in response to community feedback, we've extended the application deadline for the Policy subcommittee to Monday, August 29th at 5pm Pacific (Monday midnight UTC). Looking forward to discussing the many thoughtful comments we've received during our upcoming Lab Meeting - Tuesday, August 16th at 1pm UTC and 10pm UTC.

**Comment by ctb** [comment]
Hi @jduckles @ErinBecker I just saw the new [CoC enforcement manual](http://www.datacarpentry.org/CoC-enforcement/).  While I don't have any specific objections to the policies, I'd like to point out that I never heard back about the proposals in this issue (which I asked a board member to raise in June). At this point, I don't know if the proposals in this issue were raised and discussed and incorporated, or if they were never raised, or ...what happened.  It does seem like the final enforcement policy fails to address at least one issue here, and really fails to address several of the points above about quick response.

At a minimum I think this issue should be updated or closed, and https://github.com/swcarpentry/board/pull/115 and https://github.com/swcarpentry/board/pull/116 should be updated or closed.

**Comment by ErinBecker** [comment]
@ctb @jduckles @pbarmby Thanks Titus for re-flagging the GitHub issues related to the CoC. You're absolutely right that the comments on these issues should be responded to directly. It has taken many, many conversations with many members of the community to come to the policy that was finally adopted. It's important for us to take the time to acknowledge all those whose contributions helped shape the final policy.

I've just reached out to the other members of the Policy subcommittee to help respond to each of these comments here. I can say in general that the conversations that took place here (and in the other issues you referenced) and on Discuss before the conversation was moved to GitHub were reviewed by the Policy committee and used as input when developing the new policies. Due to the diversity of opinions represented, the committee was not able to incorporate all suggestions  into the final document, but we did make the effort to address the issues raised by the community.

You specifically mention that you feel the new CoC fails to address the point about quick response. When considering this issue, we attempted to balance the need for the ability to respond quickly to dangerous or otherwise hazardous situations against the importance of avoiding unnecessary unilateral action. We decided to allow unilateral action by single committee members in any case where there is a threat to safety or the action is ongoing. In any case where a unilateral action is taken, the actor must report their actions to the rest of the committee within 24 hours. We decided on this policy so that fast action can be taken when needed (including by full-time staff members, as Jonah and I are both on the subcommittee), while still providing oversight and avoiding any potential over-use of powers. 

I hope that this helps clarify how the issues you and others raised about response time were used to help shape the final policy. Again, I plan on working with the other members of the committee to go back through the comments here and address directly how they were incorporated (or sometimes not) into the final version of the policy. Thanks again for reviving these issues.

**Comment by ctb** [comment]
thanks for the response, @ErinBecker!

I am frustrated by the lack of engagement around these formally submitted and
discussed issues, but at least with respect to the CoC discussion I think that
ship has sailed.  In the meantime I don't personally think going over things in
detail is worthwhile, and you should just close the issues with a #wontfix
flag.  (I'm happy to support it & engage if others things it'd be useful, it's
just not a priority for me.)

Out of curiousity, *is* there a place where we can formally submit issues to be
brought before either or both of the Carpentry boards, and then get feedback
or directions for further action back in response?

**Comment by ErinBecker** [comment]
@ctb Sorry Titus, I think I must have misunderstood your point of concern.

These issues were brought to both of the Carpentry Steering Committees and it was decided to put together a subcommittee to focus on bringing together all of the thoughts from the community into a concrete policy. We had a Community Call/Lab Meeting about the CoC and about looking for members for the subcommittee back in I believe August (I'd have to check the calendar). At that point we had a lot of public interest in resolving these issues. We then put out a call for volunteers to be on the committee and received applications. These applicants were then formed into the current committee who have spent some time now bringing together the community's thoughts and forming a cohesive policy. 

The Community Call and call for volunteers were advertised on several SWC/DC communication channels. I sincerely apologize if we missed segments of the community when communicating about the path forward on these issues, as that was definitely not the intention and we were trying very hard to get feedback from the community at all steps. 

It was always our intention to treat these issues seriously and not to go behind anyone's back in resolving them. It's not my feeling that a #wontfix flag is appropriate here, as I believe we have resolved the issues of transparency and fairness that were raised by the community in response to this CoC incident, again, inviting input and action from the community at each step. I'm sorry to hear that you feel this process was lacking and welcome any suggestions you have for improving our communication and community engagement on these types of issues.

**Comment by wking** [comment]
On Wed, Nov 16, 2016 at 01:20:34PM -0800, Erin Becker wrote:
> These applicants were then formed into the current committee who
> have spent some time now bringing together the community's thoughts
> and forming a cohesive policy… I'm sorry to hear that you feel this
> process was lacking and welcome any suggestions you have for
> improving our communication and community engagement on these types
> of issues.

I expect the concern was that once the committee was formed it didn't
reach back here and update this issue, #115, or #116 as it considered
the suggestions.  Instead, the committee (which was formed very
openly) seems to have operated mostly in the dark (e.g. without
posting draft proposals here, publishing minutes like [1], etc.).
That makes it hard for folks who are interested in the issue, but not
interested enough to join the committee, to follow along or provide
input.

[1]: https://github.com/swcarpentry/board/tree/master/subcommittees/mentoring/minutes

**Comment by ctb** [comment]
These issues were brought to both of the Carpentry Steering Committees and it was decided to put together a subcommittee to focus on bringing together all of the thoughts from the community into a concrete policy. We had a Community Call/Lab Meeting about the CoC and about looking for members for the subcommittee back in I believe August (I'd have to check the calendar). At that point we had a lot of public interest in resolving these issues. We then put out a call for volunteers to be on the committee and received applications. These applicants were then formed into the current committee who have spent some time now bringing together the community's thoughts and forming a cohesive policy.

Oh, cool, I had no idea that the general CoC discussion process was linked to this issue! That's mostly what I was wondering about since this issue wasn't updated for several months and then only with a link to the new CoC.
> It was always our intention to treat these issues seriously and not to go behind anyone's back in resolving them. It's not my feeling that a #wontfix flag is appropriate here, as I believe we have resolved the issues of transparency and fairness that were raised by the community in response to this CoC incident, again, inviting input and action from the community at each step. I'm sorry to hear that you feel this process was lacking and welcome any suggestions you have for improving our communication and community engagement on these types of issues.
> 
I was using #wontfix as a sign to other readers that the specific proposals here had been moved into a larger discussion of the CoC and this issue was no longer relevant - that's how we've used it in other github issues trackers. In any case these comments do a fine job of explaining that so I'd still suggest the issue be closed, along with the other linked pull requup sets (unless more remains to b done ;).

I have no concerns about intentionally going behind anyone's back! But some guidance on how to raise issues with the boards, get feedback from them, and basically know that an issue has not ben dropped by accident would be welcome.

**Comment by wking** [comment]
On Wed, Nov 16, 2016 at 01:47:41PM -0800, W. Trevor King wrote:
> I expect the concern was that once the committee was formed it
> didn't reach back here and update…

So the issues going forward are:

* How can non-members stay involved in requests submitted to the
  steering or subcommittees?  Should they open swcarpentry/board
  issues/PRs?  Do they have to join the subcommittee?  Do something
  else?

* How can subcommittees keep non-members informed of their activity?
  There's previous discussion around this in #15 and #20, and the
  consensus seems to be that subcommittees can do whatever they want
  in terms of publishing their activity, with non-members following
  along via the steering committee minutes for any actions that the
  steering committee takes based on subcommittee advice.  Grepping
  around, I see [1,2] in the steering committee minutes, but nothing
  about the October activity.  On the other hand, the current steering
  committee minutes only get us through Oct. 6th, so there may be more
  notes coming out in the next few weeks.

[1]: https://github.com/swcarpentry/board/blob/2a445e6126833951aa19dc6c3517879b196414ff/minutes/minutes-2016-05-09.md#motion-2016-05-094
[2]: https://github.com/swcarpentry/board/blob/2a445e6126833951aa19dc6c3517879b196414ff/minutes/minutes-2016-07-07.md#motion-2016-07-071

**Comment by ctb** [comment]
I think @wking has correctly channeled my larger concerns, but that discussion should probably move to a new issue... I'd suggest linking back to this one so people can follow it.

**Comment by PBarmby** [comment]
Thanks all for this. As committee chair I take some of the blame for not updating people on what was going on. I or someone else from the CoC committee will circle back on this and update the relevant issues, hopefully within the next week.

**Comment by hlapp** [comment]
So @ErinBecker posted a link here to a blog post, and another FYI and reminder about the subcommittee being formed, and that those who care deeply about the issue can apply to have a say. If you care enough about the issue to wanting to have a say, why did you not respond to that call?

Surely there are things here communication-wise that could have been done more perfectly, but at least from my vantage point they not only meet but exceed what I would define as _good_.

Are we sure we aren't raising issues here solely because there isn't yet a policy that could cover every hole, but because something went really the wrong way and we need to prevent it from going that way again? I'm skeptical.

**Comment by wking** [comment]
On Thu, Nov 17, 2016 at 02:31:42PM -0800, Hilmar Lapp wrote:
> If you care enough about the issue to wanting to have a say, why did
> you not respond to that call?

This is a reasonable position, but I don't think it's clearly the
*default* approach.  In #140 (where I try to find ways around these
communications in the future) it's the “Another approach would be to
ask folks who were interested in ongoing discussion to join the
subcommittee…” case.  Whatever approach we decide on in #140, I think
this repo should get some docs documenting it.

> Are we sure we aren't raising issues here solely because there isn't
> yet a policy that could cover every hole…

Are you talking about the CoC policy?  Or about the
issue-submission-and-subsequent-discussion policy?

> … but because something went really the wrong way and we need to
> prevent it from going that way again? I'm skeptical.

I don't think anything went terribly wrong, but I think future
communiciation between (sub)committees and non-members could be
better.  #140 has some ideas on that front.  But communication could
always be better ;).  In most cases it's neither terrible nor
unexpected when it breaks down a bit.

**Comment by tracykteal** [comment]
Thanks @wking @ctb for raising this issue. As you suggested, there's always room for improvement in communications, and it's an important part of any organization, especially one as community engaged as our's. Good communication is something we're committed to, and you can see some of our work on that with the new 'announce' list, our community calls, monthly newsletter, our [assessment efforts](http://www.datacarpentry.org/assessment/) (where we've published the report with DOI and all the data), publishing [all our talks](https://www.zotero.org/groups/datacarpentry) and subcommittee and Steering Committee reports (although we need to be sure to get these out in a timely manner). Data Carpentry is also focusing more on our blog and updating it with activities, something that our Associate Director is taking leadership on now that she's back from parental leave. The next thing we're working on are these more informal modes of discussion around ongoing activities that you mention. 

One of the other challenges there is the distribution of information across websites, Google docs, Github issues, email lists, personal email threads, blog posts, Slack and Twitter. It's a challenge for both the posters and communicators of information and the people who are interested in the information. It's a challenge not easily solved because members of the community have different preferences and needs for the way they look for and receive information. For instance, for the CoC subcommittee, they were updating the Google doc where they'd asked for comments, and switched over to that mode of communication, but then we didn't come back to the github issues. 

It's naive to think a technical solution can solve all the things, but something that might be useful to think about is an aggregated 'updates' website and RSS feed that would put all of those updates in one place. Admittedly that would mean that it was all the updates and not the updates on a specific topic, but the top of the updates page could provide links to the different initiatives, so people could find information there. So there would be a 'push' component where people could get all the updates by just subscribing and 'pull' component where people could seek out information on the topics they're interested in. 

We'd be happy to hear suggestions both technical and social around communications. We know we're not there yet, and we make mistakes, but our goal is to operate as transparently as possible with broad community engagement.

**Comment by ctb** [comment]
The discussion and suggestions here were taken into account during the development of the new CoC manual per [comment](https://github.com/swcarpentry/board/issues/114#issuecomment-261075609).
