### ISSUE TITLE
Proposal for Lesson Infrastructure subcommittee

### ISSUE THREAD

**Issue by k8hertweck** [swcarpentry/board#155]
**Proposal for Lesson Infrastructure Subcommittee**

This proposal follows the expectations/subheadings outlined in the [subcommittee proposal instructions](https://github.com/swcarpentry/board/blob/master/subcommittees/proposal_instructions.md), and is being submitted in conjunction with a proposal to revise the lesson maintainers (#154).

**Current description of lessons subcommittee**: [website](http://software-carpentry.org/join/subcom/maintainers/), [board repo](https://github.com/swcarpentry/board/blob/master/maintainers.md), also related to [old lesson organization committee](https://github.com/swcarpentry/board/tree/master/subcommittees/lessons)

**Specific goals**

- Manage lesson release process and coordinate lesson releases
- Group decision-making for any changes that will affect more than one lesson
- This applies to lessons officially described as “supported” by the Carpentries
- Maintenance of the following general repositories: 
1. [styles](https://github.com/swcarpentry/styles)
2. [lesson-example](https://github.com/swcarpentry/lesson-example)
3. [workshop-template](https://github.com/swcarpentry/workshop-template)
- Not responsible for decisions about development or adoption of new lessons, as this falls under the [lesson incubation process](https://software-carpentry.org/lessons/incubation/)

**Steps**

- Review issues and PRs for repositories described above
- Determine workflows for general issues related to lesson maintenance
- Communicate with all maintainers about changes to general repositories and common workflows

**Timeline**
Meet quarterly

**Measuring success**

- Continuation of functional, continually improved lesson framework
- Increased participation from community in lesson maintenance

**Members**
Kate Hertweck
Naupaka Zimmerman
Maneesha Sane
Raniere Silva
Rémi Emonet
Greg Wilson
Tracy Teal
Gabriel Devenyi

**Budget**
N/A

**Comment by rgaiacs** [comment]
@k8hertweck Thanks for this issue and #154. Can I suggest to have only the Lesson Subcommittee and a "core" for it? The Lesson Subcommittee is formed by lesson maintainers (so far up 2 per lesson) and `*` Carpentry office. The "core" is formed by the chair and vice-chair of the Lesson Subcommittee, one maintainer of the templates, one maintainer of the Python lesson**s**, one maintainer of the R lesson**s**, one maintainer of the Shell/Git/OpenRefine/... lesson**s**, one maintainer of the Instructor Training lesson.

The "core" will review issues and PRs for styles, lesson-example and workshop-template repositories, determine workflows for general issues related to lesson maintenance, and communicate with all maintainers about changes to general repositories and common workflows **every quarter**. The composition of the "core" is design to ensure that the favourite tool of one community will not take over our workflow without good reasons (e.g. use `*` notebook format).

Each maintainer will review and merge PRs for assigned repo (both content and templates), guide discussions around development and evolution of content for assigned lessons, manage issues for assigned repo, review communications from Lesson Infrastructure Subcommittee and implement guidelines as recommended. Maintainers are welcomed to attend the quarter meeting but don't have vote right.

"core" members can change quarterly to avoid overload the members.

@k8hertweck As you can see, I agree with you on the format! :-) I only want to suggest a different name format. :-)

**Comment by k8hertweck** [comment]
Thanks for the comments, @rgaiacs! As you've noted, there are clearly procedural issues we need to resolve and document, and you've made some great suggestions that I'm happy to include in our subsequent discussions. After a bit more feedback, I'll start the PR that creates/revises directories in the board repo to house documents outline things you've described here.

Part of the reason we defined this group as "Lesson Infrastructure" is to separate responsibilities from lesson maintainers and also leave room for further separation (sometime in the future) into a group that may determine curriculum and overall lesson content (right now, those decisions are largely left to maintainers, but this isn't fully described). @tracykteal, do you think this represents our last discussion on this issue?

**Comment by wking** [comment]
On Tue, Dec 20, 2016 at 07:15:15AM -0800, Kate Hertweck wrote:
> 1. [styles](https://github.com/swcarpentry/styles)
> 2. [lesson-example](https://github.com/swcarpentry/lesson-example)
> 3. [workshop-template](https://github.com/swcarpentry/workshop-template)

These seem orthogonal enough to me that we should assign them
maintainers independently.

> **Timeline**
> Meet quarterly

Repository maintaince is usually asynchronous.  While occasional
synchronous meetings, polls, or votes are useful to push sticky issues
through to consensus (where you've been unable to reach a consensus
asynchronously), I don't think we need to pick a frequency for them
here.  Maintainers wrestling with a sticky issue can organize
meetings, polls, or votes as needed.

To @rgaiacs communication comments, I think it's the responsibility of
any repo maintainer (styles, template, or specific lessons) to cut
periodic releases with summaries of what's changed since the last
release.  You shouldn't need quarterly “here's what's changed”
updates, just cut a new release (with release notes) when you land
important changes.  And when you are planning important changes, make
sure you noise it about in your PR and on maintainers@ so that
interested parties have time to raise any concerns.

**Comment by tracykteal** [comment]
Thanks @k8hertweck I think this reflects our discussion. As @wking notes, 'workshop-template' might be out of scope, so it could be excluded, although it would then have no other official oversight, so I think it could go either way. 

The idea here as both @rgaiacs and @k8hertweck mention is that this is overseeing template changes, the infrastructure around the lessons, rather than any content within the lesson themselves or individual lessons. For that periodic discussions are useful, so they can evaluate as a whole what's working, what's not and make sure to be paying attention to any comments being made across all the repositories. 

This subcommittee is separate from lesson maintainers, and they can obviously meet as needed or do things asynchronously. 

As far as I know Software Carpentry is committed to coordinated bi-yearly releases, and Data Carpentry will also soon be on that schedule, so the releases are planned and coordinated. This follows a shown-to-be effective strategy that the Eclipse Foundation uses (https://wiki.eclipse.org/Simultaneous_Release) and is also important when lessons connect with each other, as they do for Data Carpentry.

**Comment by wking** [comment]
On Tue, Dec 20, 2016 at 04:28:51PM -0800, Tracy Teal wrote:
> As @wking notes, 'workshop-template' might be out of scope, so it
> could be excluded, although it would then have no other official
> oversight, so I think it could go either way.

I think it should still have oversight.  Just have the Steering
Committee appoint maintainers.  And if you want, you could grant those
maintainers the right to manage the maintainer set (with the SC
retaining the right to clobber the maintainer set in the unlikely
event that things go crazy).  For an example of this sort of workflow
in another community, see [1,2].  You don't need to be a subcommittee
to have SC oversight.

> The idea here as both @rgaiacs and @k8hertweck mention is that this
> is overseeing template changes, the infrastructure around the
> lessons, rather than any content within the lesson themselves or
> individual lessons.

Yeah, you definitely want independent governance of the template(s)
vs. the lessons themselves.

> For that periodic discussions are useful, so they can evaluate as a
> whole what's working, what's not and make sure to be paying
> attention to any comments being made across all the repositories.

Presumably lesson maintainers for whom the templates are not working
can file template issues with “$A is not working because $B” or “I'd
like to move in direction $C because $D”.  And you should reach out to
maintainers (via maintainers@ and cook time on template PRs) when
you're about to make an important template change.  Once you have both
of those (and we seem to already?), I don't know what you'd talk about
in a periodic meeting.

> As far as I know Software Carpentry is committed to coordinated
> bi-yearly releases…

Non-coordinated releases are also an effective strategy [3].  And of
course, sometimes you do have to coordinate releases to handle
interdependencies, but I'm fine leaving that up to the maintainers of
the interdependent lessons.  But assuming that all the maintainers do
decide (or are required to) cut bi-yearly releases, I'm still not sure
you'd accomplish that more effectively by involving a meeting.  For
example, you can asynchronously tag for a given milestone [4,5,…].

[1]: https://www.opencontainers.org/about/governance
     Especially §5.  And their wording in here is not particularly
     consistent, but in practice they've ended up with a separate repo
     and maintainer set for each OCI Project.
[2]: https://github.com/opencontainers/project-template/blob/9f95b15139365f60f27e5cc3028ddad20429a5fe/MAINTAINERS_GUIDE.md#how-are-maintainers-added
[3]: https://packages.gentoo.org/
[4]: https://github.com/swcarpentry/git-novice/milestone/2
[5]: https://github.com/swcarpentry/lesson-example/milestone/2

**Comment by k8hertweck** [comment]
It sounds like there isn't strong opposition to keeping workshop-template under this umbrella, since it is a student-facing part of our material that only requires intermittent updates but should still have consistent, clear oversight.

I agree in principle with the workflow you've described above, @wking, but feel like many folks (myself included) have been dissatisfied with the process over the last year or so. Part of that may be because much of our community doesn't have previous experience with the software development community, and aren't as accustomed to working asynchronously. The ideas expressed by @rgaiacs and @tracykteal above describe a workflow with regular, expected intervals that will also help us inform the community of relevant changes.

I feel like some of these ideas are starting to coalesce, and I'll try opening a PR within a few days that fits this subcommittee into the template framework of the others.

**Comment by wking** [comment]
On Tue, Dec 20, 2016 at 05:55:25PM -0800, Kate Hertweck wrote:
> The ideas expressed by @rgaiacs and @tracykteal above describe a
> workflow with regular, expected intervals that will also help us
> inform the community of relevant changes.

If folks feel like regular meetings will help with communication
(between template maintainers and lesson maintainers?  Between lesson
maintainers and instructors?), I don't have a problem with them.  I
just don't think they should be the foundation of the maintenance
plan.

A subcommittee with eight members covering three template repositories
and (new?) documentation locations is both a large group of people and
a large amount of responsibility.  Without more tightly-focused
responsibilities, I think we'll end up with situtation where ideas
just sit around waiting for someone to take ownership (to pick on an
example at random, see swcarpentry/styles#93 with a months-old fix in
an @rgaiacs comment).  Volunteer projects are always going to be
understaffed, so keeping a narrow focus (e.g. two or three maintainers
per repo, and not too many repos per maintainer) will make it easier
for maintainers to keep up, and easier for non-maintainers to gently
prod the maintainers when they fall behind ;).  It will also help the
Steering Committee notice when a particular maintainer is overloaded
and could use a responsibility reduction/focusing (“we see issues
piling up in swcarpentry/foo.  Maybe you want to focus on
swcarpentry/bar and let Active Newcomer take your place as a foo
maintainer?”).

So as long as the repositories end up with clear (and hopefully small)
maintainer sets I'll be happy.  If folks want to put a subcommittee on
top of that, I don't mind one way or the other, although spelling out
the interaction between the subcommittee and the template repo
maintainers might be tricky.  Maybe the subcommittee appoints the
template repo maintainers?  Maybe the template repo maintainers are
appointed by the Steering Committee and the subcommittee just
organizes meetings to bring the template repo and lesson maintainers
together?  Or the subcommittee brings lesson and template maintainers
together with instructors?  Or something else?

**Comment by rgaiacs** [comment]
Approved as Motion [#2017-01-04/3](https://github.com/swcarpentry/board/blob/master/minutes/minutes-2017-01-04.md#motion-2017-01-043).
