### ISSUE TITLE
Rename "standing subcommittees" to "working groups"?

### ISSUE THREAD

**Issue by wking** [swcarpentry/board#17]
Yesterday @katyhuff [posted a plan for subcommittees][1] that are lead by a steering committee member but have non-committee members as well.  Since the membership isn't a subset of the steering committee, I'd prefer we not use the name “[subcommittee][2]”.  “[Working group][3]” or “[advisory board][4]” seem like better fits.

[1]: http://software-carpentry.org/blog/2015/03/scf-subcommittees.html
[2]: http://en.wikipedia.org/wiki/Committee#Subcommittees
[3]: http://en.wikipedia.org/wiki/Working_group
[4]: http://en.wikipedia.org/wiki/Advisory_board

**Comment by katyhuff** [comment]
I get your point. 
Thoughts:

- Working group is reasonable to me, except that changing the name now might confuse folks (sorry, it's been announced, so we may just have to live with this name even though it annoys you?)
- Advisory board is out. NumFOCUS can't allow us to use the word "board" for any of these groups because they have their own board and we are under their org umbrella. [This repo is named board because it formed before we made an agreement with numfocus. Changing the name would be confusing, so we're somewhat stuck with it. See above.] Additionally, we have an Advisory Council (parallel with the Steering Committee, but composed of representatives from among our organizational members and other stakeholders.)

**Comment by jiffyclub** [comment]
I really don't care whether these are called subcommittees or working groups, but now is definitely not a good time to change up the terminology. It's something we can revisit at a calmer moment.

**Comment by wking** [comment]
On Fri, Mar 06, 2015 at 01:28PM -0800, Matt Davis wrote:
> …but now is definitely not a good time to change up the terminology…

The right time to sort out the naming is before the splashy
announcement ;).  After that, I think it just gets harder and harder.
Revisiting it later probably isn't worth it, since as @katyhuff points
out, we haven't renamed this repository to avoid confusing people
(even though the “board” is not the “steering committee”).  The sooner
we rename it, the fewer folks we confuse.  This particular instance
isn't very important, but personally I'd just fix it ;).  If the
consensus is (as it seems to be) “just live with the fact that they're
not actually subcommittees” then that's fine too.  If they actually
are just public advisory bodies to inform committee members for their
committee-side activities, then subcommittees is probably a good
choice (but I'm not clear on the actual role, see #19).

**Comment by katyhuff** [comment]
They are internal advisory bodies.

**Comment by wking** [comment]
On Fri, Mar 06, 2015 at 01:39:36PM -0800, Katy Huff wrote:
> They are internal advisory bodies.

Ah, “standing subcommittees” sounds great then :).  Sorry for my
confusion over their intended role :p.
