### ISSUE TITLE
Provide more details on the purpose, infrastructure, and rules around subcommittees / working groups

### ISSUE THREAD

**Issue by wking** [swcarpentry/board#19]
Yesterday @katyhuff [posted a plan for subcommittees][1].  I'd previously expected subcommittees to just be informal subsets of the steering committee.  Since informal subgroups don't really need their own rules (there are only seven members on the whole committee), the sparse description in `committee-roles.md` seemed sufficient.  However, given the larger scope and more free-form community involvement outlined in the blog post, I think it makes sense to have a permanent location (see also #18) that gives more details on the groups.  Stuff I'd like to see:

* Examples of the actions that the group takes.  For example, the blog post has “The Lesson Organization and Development subcommittee oversees and directs development, organization, and maintenance of the Software Carpentry curriculum materials.”.  Is it directing development by advising the swcarpentry/lesson-template maintainers?  By appointing and overseeing the swcarpentry/lesson-template maintainers?  By *being* the swcarpentry/lesson-template meintainer?  By advising the steering committee on matters pertaining to lesson development?

* Logs of the group's past actions and discussions.  This would help clarify the previous point (once there's a history to log), but it's still good to have a better summary.  Public logs are mostly useful for creating a transparent system so folks know:

    * What options were discussed
    * Why a particular option was chosen in preference to its alternatives
    * Who's doing the choosing

 That sort of transparency helps folks understand where the project is headed in the future, and demonstrates (hopefully) a good balance of collecting input from many perspectives and then making reasonable decisions grounded in that input and addressing potential issues.

* Methods for contacting / joining the group.  This may overlap with the logs, if the channel is a public mailing list or GitHub issue tracker.  The blog post suggests people mail `board@`, but when I did that @katyhuff suggested (reasonably, in my opinion) “to avoid inbox clutter for the rest
of the steering committee, can you please take detailed discussions of the subcommittee offlist?”.  Having a dedicated channel (even if that's just a personal email address for the group's lead) would make more sense to me than pointing people at `board@` and then redirecting them somewhere else.

[1]: http://software-carpentry.org/blog/2015/03/scf-subcommittees.html

**Comment by katyhuff** [comment]
> I'd previously expected subcommittees to just be informal subsets of the steering committee. Since informal subgroups don't really need their own rules (there are only seven members on the whole committee), the sparse description in committee-roles.md seemed sufficient. 

These are very much small informal groups. These subcommittees should not be so heavily constrained as you are suggesting, or they will never get anything done. I would prefer to see them manage their own internal coordination and be able to discuss options without the distraction of complex beureaucratic overhead and unmoderated public interruption. 

> Examples of the actions that the group takes.

This is decidedly impossible at this stage. The groups have not yet created their own charters yet (with the exception of finance, the charter for which is under discussion), so it is impossible to say with any detail how they will undertake each of their challenges. Once they create their own charters, then those will be recorded in the Steering Committee minutes (because they will report those charters to the Steering Committee.)

> Logs of the group's past actions and discussions. 

All suggestions they make will be recorded in the Steering Committee minutes because any actual changes to SCF policy resulting from their discussions will be voted on by the Steering Committee. They are expected to have discussions that advise the steering committee and it is hoped that they will enact policies adopted by the Steering Committee. Updates on their actions will be given by the SCF liasons at Steering Committee meetings and will be therefore recorded in the minutes. This has *already* taken place and will appear the in the most recent minutes (which are currently undergoing approval as part of our process).
 
> Methods for contacting / joining the group.

The blog post was very clear about how we hope people to contact the steering committee liaisons to the groups and how to join the groups. Sharing personal emails for the SCF liaisons is a privacy issue. We have shared their names instead and given an email list (board@software-carpentry.org) to which they are all subscribed.

Will this solution work for you: I can add an issue tag for each subcommittee to this repo. The committees will then have access to those issues tagged with the committee name.

**Comment by jiffyclub** [comment]
To address your first bullet, I think the role of most of these subcommittees is to advise the steering committee on pertinent matters as they come up. Speaking as the lead of the lessons subcommittee, I can say that our exact charter and agenda is very nebulous at this point and I expect it to grow organically as new challenges come before the steering committee. At this point I'm thinking of the lessons subcommittee as a brain trust.

**Comment by wking** [comment]
On Fri, Mar 06, 2015 at 01:27PM -0800, Katy Huff wrote:
> > I'd previously expected subcommittees to just be informal subsets
> > of the steering committee. Since informal subgroups don't really
> > need their own rules (there are only seven members on the whole
> > committee), the sparse description in committee-roles.md seemed
> > sufficient.
>
> These are very much small informal groups.

Ah.  Maybe I just misunderstood the announcement kicking off a series
of similar informal groups all at once ;).  With the “brain trust”
role @jiffyclub is mentioning, all of these issues become less
pressing.

> These subcommittees should not be so heavily constrained as you are
> suggesting, or they will never get anything done.  I would prefer to
> see them manage their own internal coordination and be able to
> discuss options without the distraction of complex beureaucratic
> overhead and unmoderated public interruption.

I don't think posting a subcommittee description and discussion logs
in a public place is a particularly tight constraint ;).  But maybe
this is spilling into #20, which I just spun off as its own issue?

> > Examples of the actions that the group takes.
>
> This is decidedly impossible at this stage. The groups have not yet
> created their own charters yet…

So currently “creating a charter” is one action, and the rest is
postponed until after that has happened.  Do we have ground rules
limiting those charters?  If the purpose is just to advise the
committee, I don't see why you'd need a charter at all.

> > Logs of the group's past actions and discussions.
>
> All suggestions they make will be recorded in the Steering Committee
> minutes because any actual changes to SCF policy resulting from
> their discussions will be voted on by the Steering Committee.

I'm not just interested in the actual changes and vote results, I'm
also interested in the discussion behind them.  I think this also
falls under #20.

> > Methods for contacting / joining the group.
>
> The blog post was very clear about how we hope people to contact the
> steering committee liaisons to the groups and how to join the
> groups.

Right, but it was already creating off-topic friction on board@, so I
thought there should be another channel.  @jiffycub pointed out that
there aren't plans for ongoing recruitment [1], so finding better
channels shouldn't be an issue.

> Will this solution work for you: I can add an issue tag for each
> subcommittee to this repo. The committees will then have access to
> those issues tagged with the committee name.

If the (or a) subcommittee discussion channel is via GitHub issues,
then I think it makes more sense to have per-subcommittee
repositories.  That makes it easier for folks to subscribe (or not) at
the subcommittee level.  If we keep them all in here, it may get a bit
chatty (e.g. I'm not really interested in the finance subcommittee's
discussion.  I know it's critically important, and I appreciate the
effort put in by its members, but it's just not my thing ;).

[1]: https://github.com/swcarpentry/board/issues/18#issuecomment-77644270

**Comment by katyhuff** [comment]
> So currently “creating a charter” is one action, and the rest is
postponed until after that has happened.  Do we have ground rules
limiting those charters?  If the purpose is just to advise the
committee, I don't see why you'd need a charter at all.

In the way I meant to use it, "charter" was a synonym for your "Examples of the actions that the group takes." That is, "stuff the committee intends to do". I was trying to use just one word to mean the things that you said in your paragraph of questions about examples. The way I read your question, you were asking for me to provide you with all of the charters for all of the committees. All I am saying is that you have to just wait because how they create a notion of their mission, what it looks like, how detailed it is, and whether it is written on papyrus or in tattoos on the skulls of its members has not yet been decided. Mission development will be left up to the subcommittees.

> If the (or a) subcommittee discussion channel is via GitHub issues,

I actually was just suggesting I would create the tags and the subcommittees could look at issues associated with their tag, **or not**, as they so choose. I am definitely not guaranteeing they will. I don't want to control these subcommittees at that level. The SC will certainly view them and potentially consider any issues in meetings if the subcommittees don't take them up. 

> I think it makes more sense to have per-subcommittee repositories

That's great. If you find yourself on a subcommittee, I hope you will create a repository for your subcommittee. For now, that decision needs to be left up to each subcommittee.

>  If we keep them all in here, it may get a bit chatty

I think I'm getting an idea of what you mean.

**Comment by katyhuff** [comment]
Labels created.

**Comment by wking** [comment]
On Fri, Mar 06, 2015 at 03:10PM -0800, Katy Huff wrote:
> > So currently “creating a charter” is one action, and the rest is
> > postponed until after that has happened. Do we have ground rules
> > limiting those charters? If the purpose is just to advise the
> > committee, I don't see why you'd need a charter at all.
>
> In the way I meant to use it, "charter" was a synonym for your
> "Examples of the actions that the group takes."

Heh, and again I overestimate the level of complication ;).  In that
case there's not much more you could have said other than:

  Subcommittees will primarily advise the steering committee about
  their focus topic, and may take other action at their discretion.
  The discussion forums used by the subcommittee and other operational
  details are left up to the members of the subcommittee in question.

  Information about public subcommittee activity and archives will be
  maintained in
  https://github.com/swcarpentry/board/tree/master/subcommittees.

> > If the (or a) subcommittee discussion channel is via GitHub
> > issues,
>
> I actually was just suggesting I would create the tags and the
> subcommittees could look at issues associated with their tag, or
> not, as they so choose.

Ah, that's a great idea for subcommittees without another contact
channel.  Thanks :).

> > If we keep them all in here, it may get a bit chatty
>
> I think I'm getting an idea of what you mean.

Having this discussion has really helped me understand the purpose and
organization of these subcommittees (but maybe I'm just dense ;).  In
any case, I really appreciate you and @jiffyclub reaching out and
clearing up my confusion.  If I had to guess when posting, I would
have said that these issues would be mostly notes to myself about
things I wasn't clear on.  I'm pleasantly surprised to see them
dissected and appropriately addressed or dismissed so quickly and
thoroughly.  So thanks for putting up with my chatter :).
