### ISSUE TITLE
SCF resolutions and minutes not up to date on website

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/board#203]
The list of all SCF resolutions (https://github.com/swcarpentry/board/blob/master/minutes/resolutions.md) linked to from https://software-carpentry.org/scf/
has not been updated since October 2015.

The minutes from SCF meetings have not been posted since November 2016.

**Comment by rgaiacs** [comment]
> The list of all SCF resolutions (https://github.com/swcarpentry/board/blob/master/minutes/resolutions.md) linked to from https://software-carpentry.org/scf/
has not been updated since October 2015.

This is my fault. I didn't copy and past the resolutions into https://github.com/swcarpentry/board/blob/master/minutes/resolutions.md because I disagree to duplicate stuffs.

> The minutes from SCF meetings have not been posted since November 2016.

Probably another of my faults. I forgot to mention it to @raynamharris. Would be nice to automate it to query https://github.com/swcarpentry/board/blob/master/minutes/.

**Comment by raynamharris** [comment]
I can add the links to the 2017 minutes, no problem.

However, can someone first setup the .html file to create a 2017 column? I do not feel comfortable doing that. https://github.com/swcarpentry/website/blob/gh-pages/pages/scf.html

**Comment by rgaiacs** [comment]
@raynamharris A thttps://github.com/swcarpentry/website/blob/gh-pages/pages/scf.html#L176 replace

~~~
  <div class="medium-6 columns">
  </div>
~~~

with

~~~
  <div class="medium-2 columns">
    <h3>2017</h3>
    <ul>
      <li><a href="{{page.minutes}}/minutes-2017-mm-dd.md">2017-mm-dd</a></li>
    </ul>
  </div>
  <div class="medium-4 columns">
  </div>
~~~
