### ISSUE TITLE
Add minutes of mentoring subcommittee meeting at 2015-10-09

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/board#60]
@karinlag Can you do this? This was the meeting about the mini-lesson proposal.

**Comment by karinlag** [comment]
On 18/10/15 18:57, Raniere Silva wrote:
> @karinlag <https://github.com/karinlag> Can you do this? This was the
> meeting about the mini-lesson proposal.

I am confused, this is the meeting about the Practicum proposal? I was 
not thinking of creating any minutes as such, mostly because we are 
creating a proposal based on the discussion. However, if you still want 
minutes, I will have to do that later this week, possibly the weekend.

karin

**Comment by rgaiacs** [comment]
> This is the meeting about the Practicum proposal?

Yes.

> I was not thinking of creating any minutes as such.

OK.
