### ISSUE TITLE
Guidelines for discussion sessions

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/board#72]
Discussions sessions happens before the checkout session that Instructor Training students need to attend. A guideline for the discussion session will be of great help.

**Comment by rgaiacs** [comment]
@gvwilson, @karinlag, @ChristinaLK Could any of you work on this during this week?

**Comment by karinlag** [comment]
I will be observing a checkout session next week, so I can try to write down something after that?

**Comment by rgaiacs** [comment]
In the dream world we would have this before the first round of checkout session but I know that due time constrains we will only have it for the second or third round.

**Comment by gvwilson** [comment]
Discussion should be led by trainees' questions, i.e., it should be them pulling, not the experienced instructor pushing.  If a trainee *doesn't* have at least a couple of good questions about the lesson, it's probably a sign that s/he hasn't prepared.

**Comment by karinlag** [comment]
On 05.01.2016 19:54, Greg Wilson wrote:
> Discussion should be led by trainees' questions, i.e., it should be them
> pulling, not the experienced instructor pushing. If a trainee /doesn't/
> have at least a couple of good questions about the lesson, it's probably
> a sign that s/he hasn't prepared.

I am mostly thinking as a way of framing the discussion, as in, we 
should touch on the flow of the material, how challenges work, common 
things that people have had problems with, how to prepare a lesson, etc. 
This will be a guide for the mentor, not a checklist.

I completely agree that it should be fueled by students asking 
questions, but it is harder (IMO) to get people to volunteer to guide 
these these if we don't give something to hold on to iff they should end 
up with a group that are a) woefully unprepared and/or b) just 
dreadfully quiet.

karin

**Comment by apawlik** [comment]
I'm pasting in some ideas - not sure how relevant:

Questions for discussions sessions:

1) When working through the lesson did you feel like you would like to change the flow/ present the concepts differently? If so, which ones and why?
2) Anything that you found unclear in the material? Did you get stuck anywhere?
3) What could be the misconceptions that the students could develop when learning this material? (i.e. which bits of the module may be tricky - if poorly explained, they may lead the students to broken mental model) 
4) What assumptions about the prior knowledge would have for the students taking this module? If you were to list any prerequsites, what would they be? 

1 and 2 should help the trainees get settled with our collaborative lesson development approach. That is, by answering their doubts we hopefully can retain: ["Almost all of our instructors are now using our lessons rather than legacy material of their own."](http://software-carpentry.org/blog/2016/01/eighteen-months-of-progress.html)
And of course 1 and 2 is to give trainees more confidence.

3- references back to our Instructor Training and makes trainees aware of where to be step carefully with the materials.
4 - references back to the IT as well and again, hopefully raises awareness among the trainees what is OK to assume about the prior knowledge for this module and what is not.

The problem is that the person leading the discussion needs to have good background understanding of the discussed modules.

**Comment by BillMills** [comment]
Hi @apawlik,

Just wanted to let you know I piloted these at the two discussion sessions I ran today, and they worked out great! They definitely allowed us to hit all the key points I wanted for swc-python, while being general enough to be used for all the sessions.

The only thing I like to add is some more open-ended question right at the beginning just to get people chatting, like introductions and a simple 'what did you learn' ala @gvwilson's debriefs from way back. On the topic of session leader guidance, I would also encourage session leaders to prioritize conversation even if it goes off script - if people want to chat about a tangent, that's great, because that's can really reveal nuanced thought on the topic.

Thanks again for these guidelines, I think they make a great basis for these sessions!

**Comment by apawlik** [comment]
Hi @BillMills ,

Thanks a lot for your feedback and trying these out! Very happy it was useful. I totally agree on some warm up questions and the person leading the checkout needs to be receptive to the group's needs.

I've started on putting these guidelines into the IT lessons https://github.com/swcarpentry/instructor-training/pull/111
Comments welcome!

**Comment by gvwilson** [comment]
Can this one now be closed?

**Comment by ChristinaLK** [comment]
Is this content saved/archived somewhere?  I'd like to have something to look back to if we ever start doing lesson specific discussion again...

**Comment by gvwilson** [comment]
I believe it's in 
subcommittees/mentoring/guidelines_for_checkout_discussion_sessions.md 
in the `board` repository - can you please check 
https://github.com/swcarpentry/board/blob/master/subcommittees/mentoring/guidelines_for_checkout_discussion_sessions.md 
and let me know if it's all there?
Cheers,
Greg

**Comment by ChristinaLK** [comment]
This can be closed.
